// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cross.proto

package com.landon30.crossdemo.test.proto;

public final class Cross {
    private Cross() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code protocol.msg.CrossMsgType}
     */
    public enum CrossMsgType
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <pre>
         * 去匹配服报名
         * </pre>
         *
         * <code>G_CROSS_PLAYA_SIGN_UP = 10001;</code>
         */
        G_CROSS_PLAYA_SIGN_UP(10001),
        /**
         * <pre>
         * 去匹配
         * </pre>
         *
         * <code>G_CROSS_PLAYA_MATCH = 10002;</code>
         */
        G_CROSS_PLAYA_MATCH(10002),
        /**
         * <pre>
         * 获取跨服玩家详细信息
         * </pre>
         *
         * <code>CROSS_PLAYA_PLAYER_DETAIL = 200001;</code>
         */
        CROSS_PLAYA_PLAYER_DETAIL(200001),
        ;

        /**
         * <pre>
         * 去匹配服报名
         * </pre>
         *
         * <code>G_CROSS_PLAYA_SIGN_UP = 10001;</code>
         */
        public static final int G_CROSS_PLAYA_SIGN_UP_VALUE = 10001;
        /**
         * <pre>
         * 去匹配
         * </pre>
         *
         * <code>G_CROSS_PLAYA_MATCH = 10002;</code>
         */
        public static final int G_CROSS_PLAYA_MATCH_VALUE = 10002;
        /**
         * <pre>
         * 获取跨服玩家详细信息
         * </pre>
         *
         * <code>CROSS_PLAYA_PLAYER_DETAIL = 200001;</code>
         */
        public static final int CROSS_PLAYA_PLAYER_DETAIL_VALUE = 200001;


        public final int getNumber() {
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static CrossMsgType valueOf(int value) {
            return forNumber(value);
        }

        public static CrossMsgType forNumber(int value) {
            switch (value) {
                case 10001:
                    return G_CROSS_PLAYA_SIGN_UP;
                case 10002:
                    return G_CROSS_PLAYA_MATCH;
                case 200001:
                    return CROSS_PLAYA_PLAYER_DETAIL;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<CrossMsgType>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                CrossMsgType> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<CrossMsgType>() {
                    public CrossMsgType findValueByNumber(int number) {
                        return CrossMsgType.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return Cross.getDescriptor().getEnumTypes().get(0);
        }

        private static final CrossMsgType[] VALUES = values();

        public static CrossMsgType valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private CrossMsgType(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:protocol.msg.CrossMsgType)
    }

    public interface APlayerMsgOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protocol.msg.APlayerMsg)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        boolean hasServerId();

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        int getServerId();

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        boolean hasRoleId();

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        long getRoleId();

        /**
         * <pre>
         * 角色战力
         * </pre>
         *
         * <code>optional int32 fight = 3;</code>
         */
        boolean hasFight();

        /**
         * <pre>
         * 角色战力
         * </pre>
         *
         * <code>optional int32 fight = 3;</code>
         */
        int getFight();
    }

    /**
     * <pre>
     * 跨服玩家A的报名数据
     * </pre>
     * <p>
     * Protobuf type {@code protocol.msg.APlayerMsg}
     */
    public static final class APlayerMsg extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:protocol.msg.APlayerMsg)
            APlayerMsgOrBuilder {
        // Use APlayerMsg.newBuilder() to construct.
        private APlayerMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private APlayerMsg() {
            serverId_ = 0;
            roleId_ = 0L;
            fight_ = 0;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private APlayerMsg(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            serverId_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            roleId_ = input.readInt64();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            fight_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Cross.internal_static_protocol_msg_APlayerMsg_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Cross.internal_static_protocol_msg_APlayerMsg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            APlayerMsg.class, Builder.class);
        }

        private int bitField0_;
        public static final int SERVERID_FIELD_NUMBER = 1;
        private int serverId_;

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        public boolean hasServerId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        public int getServerId() {
            return serverId_;
        }

        public static final int ROLEID_FIELD_NUMBER = 2;
        private long roleId_;

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        public boolean hasRoleId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        public long getRoleId() {
            return roleId_;
        }

        public static final int FIGHT_FIELD_NUMBER = 3;
        private int fight_;

        /**
         * <pre>
         * 角色战力
         * </pre>
         *
         * <code>optional int32 fight = 3;</code>
         */
        public boolean hasFight() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <pre>
         * 角色战力
         * </pre>
         *
         * <code>optional int32 fight = 3;</code>
         */
        public int getFight() {
            return fight_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, serverId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, roleId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt32(3, fight_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, serverId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, roleId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, fight_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof APlayerMsg)) {
                return super.equals(obj);
            }
            APlayerMsg other = (APlayerMsg) obj;

            boolean result = true;
            result = result && (hasServerId() == other.hasServerId());
            if (hasServerId()) {
                result = result && (getServerId()
                        == other.getServerId());
            }
            result = result && (hasRoleId() == other.hasRoleId());
            if (hasRoleId()) {
                result = result && (getRoleId()
                        == other.getRoleId());
            }
            result = result && (hasFight() == other.hasFight());
            if (hasFight()) {
                result = result && (getFight()
                        == other.getFight());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasServerId()) {
                hash = (37 * hash) + SERVERID_FIELD_NUMBER;
                hash = (53 * hash) + getServerId();
            }
            if (hasRoleId()) {
                hash = (37 * hash) + ROLEID_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getRoleId());
            }
            if (hasFight()) {
                hash = (37 * hash) + FIGHT_FIELD_NUMBER;
                hash = (53 * hash) + getFight();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static APlayerMsg parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APlayerMsg parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APlayerMsg parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APlayerMsg parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APlayerMsg parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APlayerMsg parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APlayerMsg parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static APlayerMsg parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static APlayerMsg parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static APlayerMsg parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static APlayerMsg parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static APlayerMsg parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(APlayerMsg prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 跨服玩家A的报名数据
         * </pre>
         * <p>
         * Protobuf type {@code protocol.msg.APlayerMsg}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protocol.msg.APlayerMsg)
                APlayerMsgOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Cross.internal_static_protocol_msg_APlayerMsg_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Cross.internal_static_protocol_msg_APlayerMsg_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                APlayerMsg.class, Builder.class);
            }

            // Construct using com.landon30.crossdemo.test.proto.Cross.APlayerMsg.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                serverId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                roleId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                fight_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Cross.internal_static_protocol_msg_APlayerMsg_descriptor;
            }

            public APlayerMsg getDefaultInstanceForType() {
                return APlayerMsg.getDefaultInstance();
            }

            public APlayerMsg build() {
                APlayerMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public APlayerMsg buildPartial() {
                APlayerMsg result = new APlayerMsg(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.serverId_ = serverId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.roleId_ = roleId_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.fight_ = fight_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof APlayerMsg) {
                    return mergeFrom((APlayerMsg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(APlayerMsg other) {
                if (other == APlayerMsg.getDefaultInstance()) return this;
                if (other.hasServerId()) {
                    setServerId(other.getServerId());
                }
                if (other.hasRoleId()) {
                    setRoleId(other.getRoleId());
                }
                if (other.hasFight()) {
                    setFight(other.getFight());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                APlayerMsg parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (APlayerMsg) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int serverId_;

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public boolean hasServerId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public int getServerId() {
                return serverId_;
            }

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public Builder setServerId(int value) {
                bitField0_ |= 0x00000001;
                serverId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public Builder clearServerId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                serverId_ = 0;
                onChanged();
                return this;
            }

            private long roleId_;

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public boolean hasRoleId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public long getRoleId() {
                return roleId_;
            }

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public Builder setRoleId(long value) {
                bitField0_ |= 0x00000002;
                roleId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public Builder clearRoleId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                roleId_ = 0L;
                onChanged();
                return this;
            }

            private int fight_;

            /**
             * <pre>
             * 角色战力
             * </pre>
             *
             * <code>optional int32 fight = 3;</code>
             */
            public boolean hasFight() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <pre>
             * 角色战力
             * </pre>
             *
             * <code>optional int32 fight = 3;</code>
             */
            public int getFight() {
                return fight_;
            }

            /**
             * <pre>
             * 角色战力
             * </pre>
             *
             * <code>optional int32 fight = 3;</code>
             */
            public Builder setFight(int value) {
                bitField0_ |= 0x00000004;
                fight_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 角色战力
             * </pre>
             *
             * <code>optional int32 fight = 3;</code>
             */
            public Builder clearFight() {
                bitField0_ = (bitField0_ & ~0x00000004);
                fight_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:protocol.msg.APlayerMsg)
        }

        // @@protoc_insertion_point(class_scope:protocol.msg.APlayerMsg)
        private static final APlayerMsg DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new APlayerMsg();
        }

        public static APlayerMsg getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Deprecated
        public static final com.google.protobuf.Parser<APlayerMsg>
                PARSER = new com.google.protobuf.AbstractParser<APlayerMsg>() {
            public APlayerMsg parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new APlayerMsg(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<APlayerMsg> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<APlayerMsg> getParserForType() {
            return PARSER;
        }

        public APlayerMsg getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface APlayerMatchMsgOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protocol.msg.APlayerMatchMsg)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        boolean hasServerId();

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        int getServerId();

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        boolean hasRoleId();

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        long getRoleId();
    }

    /**
     * <pre>
     * 跨服匹配数据
     * </pre>
     * <p>
     * Protobuf type {@code protocol.msg.APlayerMatchMsg}
     */
    public static final class APlayerMatchMsg extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:protocol.msg.APlayerMatchMsg)
            APlayerMatchMsgOrBuilder {
        // Use APlayerMatchMsg.newBuilder() to construct.
        private APlayerMatchMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private APlayerMatchMsg() {
            serverId_ = 0;
            roleId_ = 0L;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private APlayerMatchMsg(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            serverId_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            roleId_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Cross.internal_static_protocol_msg_APlayerMatchMsg_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Cross.internal_static_protocol_msg_APlayerMatchMsg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            APlayerMatchMsg.class, Builder.class);
        }

        private int bitField0_;
        public static final int SERVERID_FIELD_NUMBER = 1;
        private int serverId_;

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        public boolean hasServerId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        public int getServerId() {
            return serverId_;
        }

        public static final int ROLEID_FIELD_NUMBER = 2;
        private long roleId_;

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        public boolean hasRoleId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        public long getRoleId() {
            return roleId_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, serverId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, roleId_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, serverId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, roleId_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof APlayerMatchMsg)) {
                return super.equals(obj);
            }
            APlayerMatchMsg other = (APlayerMatchMsg) obj;

            boolean result = true;
            result = result && (hasServerId() == other.hasServerId());
            if (hasServerId()) {
                result = result && (getServerId()
                        == other.getServerId());
            }
            result = result && (hasRoleId() == other.hasRoleId());
            if (hasRoleId()) {
                result = result && (getRoleId()
                        == other.getRoleId());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasServerId()) {
                hash = (37 * hash) + SERVERID_FIELD_NUMBER;
                hash = (53 * hash) + getServerId();
            }
            if (hasRoleId()) {
                hash = (37 * hash) + ROLEID_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getRoleId());
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static APlayerMatchMsg parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APlayerMatchMsg parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APlayerMatchMsg parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APlayerMatchMsg parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APlayerMatchMsg parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APlayerMatchMsg parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APlayerMatchMsg parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static APlayerMatchMsg parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static APlayerMatchMsg parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static APlayerMatchMsg parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static APlayerMatchMsg parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static APlayerMatchMsg parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(APlayerMatchMsg prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 跨服匹配数据
         * </pre>
         * <p>
         * Protobuf type {@code protocol.msg.APlayerMatchMsg}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protocol.msg.APlayerMatchMsg)
                APlayerMatchMsgOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Cross.internal_static_protocol_msg_APlayerMatchMsg_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Cross.internal_static_protocol_msg_APlayerMatchMsg_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                APlayerMatchMsg.class, Builder.class);
            }

            // Construct using com.landon30.crossdemo.test.proto.Cross.APlayerMatchMsg.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                serverId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                roleId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Cross.internal_static_protocol_msg_APlayerMatchMsg_descriptor;
            }

            public APlayerMatchMsg getDefaultInstanceForType() {
                return APlayerMatchMsg.getDefaultInstance();
            }

            public APlayerMatchMsg build() {
                APlayerMatchMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public APlayerMatchMsg buildPartial() {
                APlayerMatchMsg result = new APlayerMatchMsg(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.serverId_ = serverId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.roleId_ = roleId_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof APlayerMatchMsg) {
                    return mergeFrom((APlayerMatchMsg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(APlayerMatchMsg other) {
                if (other == APlayerMatchMsg.getDefaultInstance()) return this;
                if (other.hasServerId()) {
                    setServerId(other.getServerId());
                }
                if (other.hasRoleId()) {
                    setRoleId(other.getRoleId());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                APlayerMatchMsg parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (APlayerMatchMsg) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int serverId_;

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public boolean hasServerId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public int getServerId() {
                return serverId_;
            }

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public Builder setServerId(int value) {
                bitField0_ |= 0x00000001;
                serverId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public Builder clearServerId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                serverId_ = 0;
                onChanged();
                return this;
            }

            private long roleId_;

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public boolean hasRoleId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public long getRoleId() {
                return roleId_;
            }

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public Builder setRoleId(long value) {
                bitField0_ |= 0x00000002;
                roleId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public Builder clearRoleId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                roleId_ = 0L;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:protocol.msg.APlayerMatchMsg)
        }

        // @@protoc_insertion_point(class_scope:protocol.msg.APlayerMatchMsg)
        private static final APlayerMatchMsg DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new APlayerMatchMsg();
        }

        public static APlayerMatchMsg getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Deprecated
        public static final com.google.protobuf.Parser<APlayerMatchMsg>
                PARSER = new com.google.protobuf.AbstractParser<APlayerMatchMsg>() {
            public APlayerMatchMsg parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new APlayerMatchMsg(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<APlayerMatchMsg> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<APlayerMatchMsg> getParserForType() {
            return PARSER;
        }

        public APlayerMatchMsg getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface APlayerDetailMsgOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protocol.msg.APlayerDetailMsg)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        boolean hasServerId();

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        int getServerId();

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        boolean hasRoleId();

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        long getRoleId();

        /**
         * <pre>
         * 角色战力
         * </pre>
         *
         * <code>optional int32 fight = 3;</code>
         */
        boolean hasFight();

        /**
         * <pre>
         * 角色战力
         * </pre>
         *
         * <code>optional int32 fight = 3;</code>
         */
        int getFight();

        /**
         * <pre>
         * 角色详细信息
         * </pre>
         *
         * <code>optional bytes roleDetail = 4;</code>
         */
        boolean hasRoleDetail();

        /**
         * <pre>
         * 角色详细信息
         * </pre>
         *
         * <code>optional bytes roleDetail = 4;</code>
         */
        com.google.protobuf.ByteString getRoleDetail();
    }

    /**
     * Protobuf type {@code protocol.msg.APlayerDetailMsg}
     */
    public static final class APlayerDetailMsg extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:protocol.msg.APlayerDetailMsg)
            APlayerDetailMsgOrBuilder {
        // Use APlayerDetailMsg.newBuilder() to construct.
        private APlayerDetailMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private APlayerDetailMsg() {
            serverId_ = 0;
            roleId_ = 0L;
            fight_ = 0;
            roleDetail_ = com.google.protobuf.ByteString.EMPTY;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private APlayerDetailMsg(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            serverId_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            roleId_ = input.readInt64();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            fight_ = input.readInt32();
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            roleDetail_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Cross.internal_static_protocol_msg_APlayerDetailMsg_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Cross.internal_static_protocol_msg_APlayerDetailMsg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            APlayerDetailMsg.class, Builder.class);
        }

        private int bitField0_;
        public static final int SERVERID_FIELD_NUMBER = 1;
        private int serverId_;

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        public boolean hasServerId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <pre>
         * 服务器id
         * </pre>
         *
         * <code>optional int32 serverId = 1;</code>
         */
        public int getServerId() {
            return serverId_;
        }

        public static final int ROLEID_FIELD_NUMBER = 2;
        private long roleId_;

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        public boolean hasRoleId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <pre>
         * 角色id
         * </pre>
         *
         * <code>optional int64 roleId = 2;</code>
         */
        public long getRoleId() {
            return roleId_;
        }

        public static final int FIGHT_FIELD_NUMBER = 3;
        private int fight_;

        /**
         * <pre>
         * 角色战力
         * </pre>
         *
         * <code>optional int32 fight = 3;</code>
         */
        public boolean hasFight() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <pre>
         * 角色战力
         * </pre>
         *
         * <code>optional int32 fight = 3;</code>
         */
        public int getFight() {
            return fight_;
        }

        public static final int ROLEDETAIL_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString roleDetail_;

        /**
         * <pre>
         * 角色详细信息
         * </pre>
         *
         * <code>optional bytes roleDetail = 4;</code>
         */
        public boolean hasRoleDetail() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <pre>
         * 角色详细信息
         * </pre>
         *
         * <code>optional bytes roleDetail = 4;</code>
         */
        public com.google.protobuf.ByteString getRoleDetail() {
            return roleDetail_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, serverId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, roleId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt32(3, fight_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, roleDetail_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, serverId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, roleId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, fight_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, roleDetail_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof APlayerDetailMsg)) {
                return super.equals(obj);
            }
            APlayerDetailMsg other = (APlayerDetailMsg) obj;

            boolean result = true;
            result = result && (hasServerId() == other.hasServerId());
            if (hasServerId()) {
                result = result && (getServerId()
                        == other.getServerId());
            }
            result = result && (hasRoleId() == other.hasRoleId());
            if (hasRoleId()) {
                result = result && (getRoleId()
                        == other.getRoleId());
            }
            result = result && (hasFight() == other.hasFight());
            if (hasFight()) {
                result = result && (getFight()
                        == other.getFight());
            }
            result = result && (hasRoleDetail() == other.hasRoleDetail());
            if (hasRoleDetail()) {
                result = result && getRoleDetail()
                        .equals(other.getRoleDetail());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasServerId()) {
                hash = (37 * hash) + SERVERID_FIELD_NUMBER;
                hash = (53 * hash) + getServerId();
            }
            if (hasRoleId()) {
                hash = (37 * hash) + ROLEID_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getRoleId());
            }
            if (hasFight()) {
                hash = (37 * hash) + FIGHT_FIELD_NUMBER;
                hash = (53 * hash) + getFight();
            }
            if (hasRoleDetail()) {
                hash = (37 * hash) + ROLEDETAIL_FIELD_NUMBER;
                hash = (53 * hash) + getRoleDetail().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static APlayerDetailMsg parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APlayerDetailMsg parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APlayerDetailMsg parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APlayerDetailMsg parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APlayerDetailMsg parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APlayerDetailMsg parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APlayerDetailMsg parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static APlayerDetailMsg parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static APlayerDetailMsg parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static APlayerDetailMsg parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static APlayerDetailMsg parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static APlayerDetailMsg parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(APlayerDetailMsg prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code protocol.msg.APlayerDetailMsg}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protocol.msg.APlayerDetailMsg)
                APlayerDetailMsgOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Cross.internal_static_protocol_msg_APlayerDetailMsg_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Cross.internal_static_protocol_msg_APlayerDetailMsg_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                APlayerDetailMsg.class, Builder.class);
            }

            // Construct using com.landon30.crossdemo.test.proto.Cross.APlayerDetailMsg.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                serverId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                roleId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                fight_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                roleDetail_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Cross.internal_static_protocol_msg_APlayerDetailMsg_descriptor;
            }

            public APlayerDetailMsg getDefaultInstanceForType() {
                return APlayerDetailMsg.getDefaultInstance();
            }

            public APlayerDetailMsg build() {
                APlayerDetailMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public APlayerDetailMsg buildPartial() {
                APlayerDetailMsg result = new APlayerDetailMsg(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.serverId_ = serverId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.roleId_ = roleId_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.fight_ = fight_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.roleDetail_ = roleDetail_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof APlayerDetailMsg) {
                    return mergeFrom((APlayerDetailMsg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(APlayerDetailMsg other) {
                if (other == APlayerDetailMsg.getDefaultInstance()) return this;
                if (other.hasServerId()) {
                    setServerId(other.getServerId());
                }
                if (other.hasRoleId()) {
                    setRoleId(other.getRoleId());
                }
                if (other.hasFight()) {
                    setFight(other.getFight());
                }
                if (other.hasRoleDetail()) {
                    setRoleDetail(other.getRoleDetail());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                APlayerDetailMsg parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (APlayerDetailMsg) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int serverId_;

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public boolean hasServerId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public int getServerId() {
                return serverId_;
            }

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public Builder setServerId(int value) {
                bitField0_ |= 0x00000001;
                serverId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 服务器id
             * </pre>
             *
             * <code>optional int32 serverId = 1;</code>
             */
            public Builder clearServerId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                serverId_ = 0;
                onChanged();
                return this;
            }

            private long roleId_;

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public boolean hasRoleId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public long getRoleId() {
                return roleId_;
            }

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public Builder setRoleId(long value) {
                bitField0_ |= 0x00000002;
                roleId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 角色id
             * </pre>
             *
             * <code>optional int64 roleId = 2;</code>
             */
            public Builder clearRoleId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                roleId_ = 0L;
                onChanged();
                return this;
            }

            private int fight_;

            /**
             * <pre>
             * 角色战力
             * </pre>
             *
             * <code>optional int32 fight = 3;</code>
             */
            public boolean hasFight() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <pre>
             * 角色战力
             * </pre>
             *
             * <code>optional int32 fight = 3;</code>
             */
            public int getFight() {
                return fight_;
            }

            /**
             * <pre>
             * 角色战力
             * </pre>
             *
             * <code>optional int32 fight = 3;</code>
             */
            public Builder setFight(int value) {
                bitField0_ |= 0x00000004;
                fight_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 角色战力
             * </pre>
             *
             * <code>optional int32 fight = 3;</code>
             */
            public Builder clearFight() {
                bitField0_ = (bitField0_ & ~0x00000004);
                fight_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString roleDetail_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 角色详细信息
             * </pre>
             *
             * <code>optional bytes roleDetail = 4;</code>
             */
            public boolean hasRoleDetail() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <pre>
             * 角色详细信息
             * </pre>
             *
             * <code>optional bytes roleDetail = 4;</code>
             */
            public com.google.protobuf.ByteString getRoleDetail() {
                return roleDetail_;
            }

            /**
             * <pre>
             * 角色详细信息
             * </pre>
             *
             * <code>optional bytes roleDetail = 4;</code>
             */
            public Builder setRoleDetail(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                roleDetail_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 角色详细信息
             * </pre>
             *
             * <code>optional bytes roleDetail = 4;</code>
             */
            public Builder clearRoleDetail() {
                bitField0_ = (bitField0_ & ~0x00000008);
                roleDetail_ = getDefaultInstance().getRoleDetail();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:protocol.msg.APlayerDetailMsg)
        }

        // @@protoc_insertion_point(class_scope:protocol.msg.APlayerDetailMsg)
        private static final APlayerDetailMsg DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new APlayerDetailMsg();
        }

        public static APlayerDetailMsg getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Deprecated
        public static final com.google.protobuf.Parser<APlayerDetailMsg>
                PARSER = new com.google.protobuf.AbstractParser<APlayerDetailMsg>() {
            public APlayerDetailMsg parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new APlayerDetailMsg(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<APlayerDetailMsg> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<APlayerDetailMsg> getParserForType() {
            return PARSER;
        }

        public APlayerDetailMsg getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protocol_msg_APlayerMsg_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_protocol_msg_APlayerMsg_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protocol_msg_APlayerMatchMsg_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_protocol_msg_APlayerMatchMsg_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protocol_msg_APlayerDetailMsg_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_protocol_msg_APlayerDetailMsg_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\013cross.proto\022\014protocol.msg\"=\n\nAPlayerMs" +
                        "g\022\020\n\010serverId\030\001 \001(\005\022\016\n\006roleId\030\002 \001(\003\022\r\n\005f" +
                        "ight\030\003 \001(\005\"3\n\017APlayerMatchMsg\022\020\n\010serverI" +
                        "d\030\001 \001(\005\022\016\n\006roleId\030\002 \001(\003\"W\n\020APlayerDetail" +
                        "Msg\022\020\n\010serverId\030\001 \001(\005\022\016\n\006roleId\030\002 \001(\003\022\r\n" +
                        "\005fight\030\003 \001(\005\022\022\n\nroleDetail\030\004 \001(\014*e\n\014Cros" +
                        "sMsgType\022\032\n\025G_CROSS_PLAYA_SIGN_UP\020\221N\022\030\n\023" +
                        "G_CROSS_PLAYA_MATCH\020\222N\022\037\n\031CROSS_PLAYA_PL" +
                        "AYER_DETAIL\020\301\232\014B#\n!com.landon30.crossdem" +
                        "o.test.proto"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_protocol_msg_APlayerMsg_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_protocol_msg_APlayerMsg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_protocol_msg_APlayerMsg_descriptor,
                new String[]{"ServerId", "RoleId", "Fight",});
        internal_static_protocol_msg_APlayerMatchMsg_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_protocol_msg_APlayerMatchMsg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_protocol_msg_APlayerMatchMsg_descriptor,
                new String[]{"ServerId", "RoleId",});
        internal_static_protocol_msg_APlayerDetailMsg_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_protocol_msg_APlayerDetailMsg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_protocol_msg_APlayerDetailMsg_descriptor,
                new String[]{"ServerId", "RoleId", "Fight", "RoleDetail",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
